services:
  - type: web
    name: aquasentinel-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG  
        value: false
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "https://*.netlify.app,http://localhost:3000"
      - key: DATABASE_URL
        value: "sqlite:///aquasentinel.db"
      - key: MODEL_PATH
        value: "./model.pkl"
      - key: SCALER_PATH
        value: "./scaler.pkl" 