services:
  - type: web
    name: aquasentinel-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG  
        value: false
      - key: PORT
        value: 10000 